#!/usr/bin/env bash
# configures nginx server to listen in on port 80

rm /env/nginx/sites-enabled/default
ln -s /env/nginx/sites-available/default /env/nginx/sites-enabled/default
service nginx restart
