#!/usr/bin/env bash                                                                                                                                                                             
# sets nginx to liste in port 80                                                                                                                                                                
                                                                                                                                                                                                
rm /etc/nginx/sites-enabled/default                                                                                                                                                             
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default                                                                                                                       
service nginx restart  
