#!/usr/bin/env bash
#Displays to infinity and beyond and i am invincible in etween each iteration

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
